### ISSUE TITLE
Trouble with CocoaPods 1.0

### ISSUE THREAD

**Issue by K-Be** [Tricertops/KeepLayout#79]
I use KeepLayout library long time, and think that it more useful then pure constrains. 
But after updating CocoaPods to 1.0, I've got compilation error: 

>  /Users/<...>/Pods/KeepLayout/Sources/KeepAttribute.m:195:1: Cannot synthesize weak property because the current deployment target does not support weak references

My pod file:
   
``` ruby
target 'MyApp' do
  platform :ios, '8.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for MyApp
  pod 'KeepLayout', :git => 'https://github.com/iMartinKiss/KeepLayout', :tag => 'v1.6.0'
  pod 'EasyMapping'

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
It's happened because CocoaPods  configures KeepLayout library target with 4.3 iOS deployment target. 
Can you add a [min deployment target](https://guides.cocoapods.org/syntax/podspec.html#deployment_target) to your CocoaPods.spec, to avoid this error?

**Comment by Tricertops** [comment]
Did it work before CocoaPods 1.0? Seems like their issue. KeepLayout declares iOS 8.0 as deployment target in project file.

**Comment by sunhr** [comment]
I also met this problem, I'm using KeepLayout 1.6.0 since my project is Objective-C only. Yesterday I upgraded CocoaPods to 1.0, and this issue came. The deployment target of KeepLayout in Pod project was set to iOS4.3.......After setting it to 8.0 manually after 'pod install', everything works fine.

I tested KeepLayout 1.7.0, there's no problem like that in 1.6.0. But I don't like to use Pods as frameworks.....TAT

**Comment by K-Be** [comment]
@Tricertops Sorry, but I can't find min deployment target in the podspec:
https://github.com/Tricertops/KeepLayout/blob/v1.7.0/KeepLayout.podspec

**Comment by K-Be** [comment]
@sunhr I use same solution. And I can't use Pods as frameworks because it setting now changes paths to the headers, for my project it can provide many hand work.

**Comment by sunhr** [comment]
@K-Be To avoid setting deployment target manually each time after pod install, I added
`s.ios.deployment_target = '8.0'` to podspec file and uploaded it to somewhere. 

And then, I have the Podfile like this
```
pod 'KeepLayout', :podspec => 'https://dn-sunhr.qbox.me/KeepLayout/KeepLayout.podspec'
```

Now everything seems to be fine.

**Comment by Tricertops** [comment]
@sunhr I was expecting someone to submit a Pull Request with that single line, not doing workarounds around CocoaPods 😄

You are complaining about _your_ dependency manager doing stupid thing and reporting that to _me_. Why the hell is CocoaPods building for iOS 4.3? Do you target your app for iOS 4.3? If not, then it’s wrong default and you should report it as bug. Do you have a way to tell CocoaPods your desired deployment target? If not, then it’s a missing feature and you should report it as bug. Why cannot CocoaPods read that info from project file? Report as a bug.

I don’t use CocoaPods. I don’t know how it works and why it works like that. I don’t even _want_ to know that. But you _do_, so fork KeepLayout, edit that Podspec file, submit a Pull Request, and I will merge it.

**Comment by K-Be** [comment]
@Tricertops  you right. I've edited podspec and created pull request: #80. 
Now I can include the library to my project with lines like this (reference to my fork of the repo): 

```ruby
target 'TestForSpecsKeepLayout' do
    pod 'KeepLayout/ObjC', :git => 'https://github.com/K-Be/KeepLayout.git', :branch => 'master'
end

target 'TestIOSSwift' do
	pod 'KeepLayout', :git => 'https://github.com/K-Be/KeepLayout.git', :branch => 'master'
	use_frameworks!
end
```

**Comment by Tricertops** [comment]
Thanks! Let’s move continue the discussion there #80
